# For secondary back-end server
version: '2.2'

services:
  postgres:
    extends:
      file: docker-compose.backend.template.yml
      service: postgres
    environment:
      - KOBO_POSTGRES_DB_SERVER_ROLE=secondary
